### ISSUE TITLE
question about 'phiVdphi'

### ISSUE THREAD

**Issue by pJahad** [mzjb/DeepH-pack#1]
Thank you for publishing the wonderful code.

I would like to ask about the meaning of variable 'phiVdphi'. 
I believe this physical quantity was not even mentioned in the DeepH paper.
If this is something that can be output from OpenMX, I would appreciate knowing how to make it.

**Comment by mzjb** [comment]
Thanks for your interest in our code. 'phiVdphi' is a feature under development. It is not related to what is mentioned in the DeepH paper and is not an output of OpenMX.

**Comment by pJahad** [comment]
Thank you for the reply!
I understand that it is under development and looking forward to a future publication.
