### ISSUE TITLE
How to calculate the eigenvalues of different k points in parallel in the inference step?

### ISSUE THREAD

**Issue by choi-geunseok** [mzjb/DeepH-pack#12]
Hello, I wonder how to calculate the eigenvalues of different k points in parallel in the inference step?

[which_k : Define which point in k-path to calculate, start counting from 1. You can set it ‘0’ for all k points, or ‘-1’ for no point. It is recommended to calculate the eigenvalues of different k points in parallel through it. (Invalid for dense matrix calculation)]

**Comment by mzjb** [comment]
If _which_k_ is set to _n_, only the eigenvalues of the _n_-th kpoint (1-based index) will be calculated. 

To calculate the eigenvalues in parallel, firstly, you can set _which_k_ to '-1' in the json config file and perform a normal inference step by _deeph-inference_ to get the necessary files (_dense_calc_ should be set to 'False' in the ini config file). You can check if _sparse matrix.jld_ is in the output directory (`${output_dir}`) of _deeph-inference_.

Then, you can prepare many json config files with different values ​​of _which_k_ in different subdirectories of `${output_dir}` (`${output_dir}/${index_k}`); and edit a bash script to run [sparse_calc.jl](https://github.com/mzjb/DeepH-pack/blob/main/deeph/inference/sparse_calc.jl) with different _which_k_ in parallel, e.g.,

```
# calc_band.sh
julia ${path_of_DeepH}/deeph/inference/sparse_calc.jl --input_dir ${output_dir}$ --output_dir ${output_dir}/1 --config ${output_dir}/1/config.json &

julia ${path_of_DeepH}/deeph/inference/sparse_calc.jl --input_dir ${output_dir}$ --output_dir ${output_dir}/2 --config ${output_dir}/2/config.json &

julia ${path_of_DeepH}/deeph/inference/sparse_calc.jl --input_dir ${output_dir}$ --output_dir ${output_dir}/3 --config ${output_dir}/3/config.json &

...

wait
```
, and run `bash calc_band.sh`.

Finally, you can get the eigenvalues of the _n_-th kpoint in the file `${output_dir}/n/openmx.Band`.

**Comment by choi-geunseok** [comment]
Thanks you for your answer.
