### ISSUE TITLE
Questions about "magnetism"

### ISSUE THREAD

**Issue by yifei-zx** [mzjb/DeepH-pack#17]
Hello，I wonder if it is possible to predict magnetic systems？

**Comment by mzjb** [comment]
Yes it is possible and we are working on it.

**Comment by qzxiong** [comment]
Hello, I read your article called "Deep-learning electronic-structure calculation of magnetic superstructures",and I'm very interested in it. Is this xDeepH currently available?

**Comment by mzjb** [comment]
Thanks for your interest. The code of xDeepH will be made available upon publication.

**Comment by mzjb** [comment]
@yifei-zx 
Hi! The xDeepH code is available at https://github.com/mzjb/xDeepH.

**Comment by yifei-zx** [comment]
Thank you,I'm really looking forward to using it.
