### ISSUE TITLE
Process killed when inferencing MATBG

### ISSUE THREAD

**Issue by peiyuan-NTU** [mzjb/DeepH-pack#19]
[network]
atom_fea_len=64
edge_fea_len=128
gauss_stop=6.0
num_l=5
aggr=add
distance_expansion=GaussianBasis
if_exp=True
if_multiplelinear=False
if_edge_update=True
if_lcmp=True
normalization=LayerNorm
atom_update_net=CGConv
trainable_gaussians=False
type_affine=False

=> load best checkpoint (epoch 3333)
=> Atomic types: [6], spinful: False, the number of atomic types: 1.
Killed

**Comment by mzjb** [comment]
Please post the ini configuration file for `deeph-inference`.

**Comment by peiyuan-NTU** [comment]
[basic]
work_dir = /home/peiyuan/test_deeph/pred_result
olp_dir = /home/peiyuan/test_deeph/data2
interface = openmx
trained_model_dir = ["/home/peiyuan/test_deeph/model"]
task = [1, 2, 3, 4, 5]
sparse_calc_config = /home/peiyuan/DeepH-pack/deeph/inference/band_config.json
dense_calc = True
disable_cuda = True
#device = cpu
device = cuda:0
huge_structure = True
restore_blocks_py = True
gen_rc_idx = False
gen_rc_by_idx =
with_grad = False

[interpreter]
julia_interpreter = julia

[graph]
radius = -1.0
create_from_dft = True

**Comment by mzjb** [comment]
How much memory does your computer have?

**Comment by peiyuan-NTU** [comment]
64G
Does it need larger memory?

**Comment by mzjb** [comment]
I haven't counted how much memory is needed to predict the Hamiltonian of MATBG. I can run it normally on a computing node with 96GB memory.
