### ISSUE TITLE
In the Inference step,,when calculating band structure, how do we get fermi level from DeepH?

### ISSUE THREAD

**Issue by peiyuan-NTU** [mzjb/DeepH-pack#20]
Will it be in the output of DeepH?

**Comment by mzjb** [comment]
The inference step computes a few eigenvalues ​​near a selected value of energy. To locate the Fermi energy, one should perform multiple sparse diagonalizations and count the occupation number of bands. This process is often much more time-consuming than calculating the few energy bands near the Fermi energy.

For magic angle twisted bilayer graphene (MATBG), in practice the Fermi energy at different twist angles are close to each other. One can use the Fermi energy for bilayer graphene with zero twist angle as a guess value, calculate the energy band of MATBG around this guess value, and locate the Fermi energy for MATBG according to the shape of the calculated energy band.

In addition, there are methods to locate the Fermi energy without diagonalization, such as using [pexsi](https://pexsi.readthedocs.io/en/latest/).

**Comment by JTaozhang** [comment]
So, if we want to get the fermi-energy,  is it means that we need to use other software to get fermi or  based on the guessing value from zero twist angle (if twisted system)?

**Comment by JTaozhang** [comment]
@mzjb
Firstly, Many thanks for your advice. But, can you provide more details on how to use sparse_calc.jl? for example, what input files  are  required and what is the executive code. I think it would be greatly helpful if there are some example to use it.  

Thanks a lot.



> @JTaozhang The most direct way to obtain the Fermi energy is to use the [sparse_calc.jl](https://github.com/mzjb/DeepH-pack/blob/main/deeph/inference/sparse_calc.jl) script in DeepH-pack. Starting from the lowest band, one can use `sparse_calc.jl` to calculate a certain number of bands, which is equal to the number of valence electrons, thus obtaining the Fermi energy. This approach does not require using other software or relying on guessed values.

**Comment by mzjb** [comment]
@JTaozhang
In fact, `sparse_calc.jl` is packaged in the `deeph-inference` command. Please refer to [this page](https://deeph-pack.deepmodeling.com/en/latest/inference/inference.html) for the usage of `deeph-inference`, and refer to [this page](https://deeph-pack.deepmodeling.com/en/latest/keyword/inference.html) for the input parameters of `deeph-inference`, which contain the parameters in `sparse_calc.jl`. Set `task=[5]` and `dense_calc=False` in parameters of the `deeph-inference` to call sparse_calc.jl individually.

**Comment by mzjb** [comment]
@JTaozhang
Both [Demo1](https://deeph-pack.deepmodeling.com/en/latest/demo/demo1.html) and [Demo3](https://deeph-pack.deepmodeling.com/en/latest/demo/demo3.html) of our documents involve the usage of this feature, please refer to these two demos for examples.

**Comment by JTaozhang** [comment]
ok. thanks. I have another three questions.
1. If I use it(sparse_calc.jl),  How I set the value of fermi_level in the Band_config.json, arbitrary designation? 
2. I notice some words ("Invalid for dense matrix calculation") in the explanation website of INPUT KEYWORDS. Is this means that, when you use dense_calc.jl, the corresponding INPUT KEYWORD is valid?
3. what is the default value of KEYWORD("dense_calc") ? I guess it is false. based on that the output file would be openmx.Band, right? and we can find the fermi-energy by using it?

**Comment by mzjb** [comment]
1. `sparse_calc.jl` calculates a few number of eigenvalues around the user-defined `fermi_level`. Therefore, you should set the input parameter `fermi_level` appropriately based on the task you are doing.
2. Yes.
3. The default value for this keyword is `True`, as indicated in [this line of code](https://github.com/mzjb/DeepH-pack/blob/1130ad648d8b02be96e9de0144f8f8cff886a178/deeph/inference/inference_default.ini#L8). The output files for both `dense_calc.jl` and `sparse_calc.jl` are `openmx.Band`. You can use these functions to calculate the Fermi energy as described above, but we do not provide the feature for automatically computing the Fermi energy. The Fermi energy displayed in the output `openmx.Band` file is simply the user-defined `fermi_level`.

**Comment by yifei-zx** [comment]
@mzjb 
hello,
I used spark_ calc.jl in inference (I set the input parameter fermi_level on the task) , but the Fermi energy in the output openmx.Band file is different fron calculated directly with openmx.

If I want to get the same energy band diagram as that calculated by openmx, how can I get the same Fermi energy level value as that in openmx calculation?

best regard.

**Comment by mzjb** [comment]
In `openmx.Band`, the units for Fermi energy and band energy are in Hartree, while DeepH uses eV as its energy unit. Please make sure that you compare energies in the same units.
