### ISSUE TITLE
In train.ini , what means about 'orbital basis number' in basic <orbital>?

### ISSUE THREAD

**Issue by Lintzuching** [mzjb/DeepH-pack#21]
Hi,
When I trying to reproduce the result of TBG in your paper  ' Deep-Learning Density Functional Theory Hamiltonian for Efficient ab initio
Electronic-Structure Calculation ' ,  I'm confused about the ' orbital basis number ' means . Does it means '  Valence electrons ' ? Or something else ? 
Regards , 
TzuChing

**Comment by mzjb** [comment]
DeepH predict DFT Hamiltonian using the [numerical localized basis](https://docs.siesta-project.org/projects/siesta/tutorials/basic/basis-sets/). `orbital basis number` means the index of the localized basis on an atom. It does not necessarily correspond to the valence electrons of materials or isolated atoms.

**Comment by Lintzuching** [comment]
Could you give me some instance? In your demo , the orbital basis number is in the region [0,18] . How about TBG ?
 What region you suggest to set ?
TzuChing

**Comment by mzjb** [comment]
For TBG, we use 13 localized basis functions for C to generate the dataset, which is the [Standard guideline choice](https://www.openmx-square.org/openmx_man3.9/node27.html) of OpenMX for C. The region in `train.ini` needs to be consistent with the number of basis functions used when generating the dataset.

**Comment by mzjb** [comment]
> Could you give me some instance? In your demo , the orbital basis number is in the region [0,18] . How about TBG ? What region you suggest to set ? TzuChing

See this [link](https://github.com/mzjb/DeepH-pack/blob/main/ini/TBG.ini) for an example ini file and this [link](https://zenodo.org/record/6555484#.Y6GOguxByz4) for the corresponding dataset.

**Comment by Lintzuching** [comment]
I'm idiot .... Thanks your nice and friendly respond !

**Comment by ismsgithub** [comment]
The [link](https://www.openmx-square.org/openmx_man3.9/node29.html) truly gives us advice on PAO selection, but I still feel confused about how to calculate `orbital basis number`? What's the formula?

**Comment by mzjb** [comment]
> The [link](https://www.openmx-square.org/openmx_man3.9/node29.html) truly gives us advice on PAO selection, but I still feel confused about how to calculate `orbital basis number`? What's the formula?

`orbital basis number` in the `ini` file just means the index of the localized basis for a atom. One does not need to  calculate it. The first basis is `0`, the second basis is `1` and so on.

**Comment by ismsgithub** [comment]
"For TBG, we use 13 localized basis functions for C to generate the dataset".  Why is 13?

**Comment by mzjb** [comment]
> "For TBG, we use 13 localized basis functions for C to generate the dataset". Why is 13?

The [Standard guideline choice](https://www.openmx-square.org/openmx_man3.9/node27.html) of OpenMX for C is C6.0-s2p2d1. 2x1+2x3+1x5=13.

**Comment by ismsgithub** [comment]
Oh, I got it. Thanks for your nice and friendly response!
