### ISSUE TITLE
The problem during the inference stage

### ISSUE THREAD

**Issue by newplay** [mzjb/DeepH-pack#24]
1. During the inference stage, is it possible to only execute task 5 and save tasks 1-4 as files for reading?Are there any parameters provided to achieve this function?

2.  When I set the band.json file, when which_k = 0, it means to use one thread to calculate all k points. Does which_k = [0,1,2,3,4,5] mean that I use one thread to calculate the first 0-5 k points? Will which_k=[0] calculate all k points or only the first k point?

Thank you for your response.
tzuching

**Comment by mzjb** [comment]
1. Yes, it is possible. Results obtained from each task is saved as files automatically.

2. `which_k` cannot be a list for now. `which_k = 1` calculates the 1st k-point. One can run a bash script to calculate multiple k-points in parallel. Just to mention, a new script for calculating bands will be released soon. It can use multiple threads to calculate one k-point.

**Comment by newplay** [comment]
Thank you , I would try to do better.
tzuching
