### ISSUE TITLE
in to     raise ValueError(f"Invalid format: `{str(fmt)}`")

### ISSUE THREAD

**Issue by JTaozhang** [mzjb/DeepH-pack#26]
Hi, There,
   when I test your example file(gen_example.py) and specified all the proper execution paths, I meet a bug (File "/public/home/ZT/software/DeepH-pack-main/gen_example.py", line 118, in <module>
    stru_shift_pert.to('poscar', f'../example/work_dir/dataset/raw/{shift_index}/POSCAR')
  File "/public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/pymatgen/core/structure.py", line 2561, in to
    raise ValueError(f"Invalid format: `{str(fmt)}`")
ValueError: Invalid format: `../example/work_dir/dataset/raw/0/poscar),  it seems the code in gen_example.py can't be recognized by pymatgen. pymatgen can't understand your code and my pymatgen version is pymatgen-2023.1.30.  if you can test it or give me some advise, I would greatly appreciate your help.

best regards,
ZT

**Comment by mzjb** [comment]
Thank you for your report.

This function has two input parameters (`fmt` and `filename`). I found that the order of these two parameters changed in different pymatgen versions.

New pyatmgen version: https://github.com/materialsproject/pymatgen/blob/ee52d534cad86abab07a82a34b3877eef5c2385b/pymatgen/core/structure.py#L2475

Old pyatmgen version: 
https://github.com/materialsproject/pymatgen/blob/b202b3b6d6a5fc7275c3f552615c912d6c2279e6/pymatgen/core/structure.py#L2338

This change caused the error: The path to the structure file is fed to the parameter representing the format of the structure file.

I  fixed it in this [commit](https://github.com/mzjb/DeepH-pack/commit/425b162aa2163977e0692e89f8691ed69e489ccd).
