### ISSUE TITLE
Necessary files could not be found in OLP_dir

### ISSUE THREAD

**Issue by yifei-zx** [mzjb/DeepH-pack#30]
Hello.
When I use openmx to calculate the overlap matrix of the predicted material, the openmx.out file is not generated, but there are output files.

when in the inference step,  it occur error as follow:

assert os.path.exists(os.path.join(OLP_dir, 'openmx.out')), "Necessary files could not be found in OLP_dir"  
AssertionError: Necessary files could not be found in OLP_dir.

How can I solve it? 
Thank you.

**Comment by mzjb** [comment]
@yifei-zx 
Please check if you have the latest version of `overlap only OpenMX` installed (https://github.com/mzjb/overlap-only-OpenMX). If not, please upgrade to the latest version. If you already have the latest version, please send me all output files from `overlap only OpenMX` except for the *.h5 file.

**Comment by yifei-zx** [comment]
This problem was solved after I updated  overlap only OpenMX to 3.9.9.
Thank you for your answer

**Comment by 1691447257-afk** [comment]
Hello, author. When I use ABACUS for calculations, it outputs the corresponding SR.CSR file. The path has been confirmed in the configuration file, but an error occurs during the prediction process:
assert os.path.exists(os.path.join(OLP_dir, 'SR.csr')), "Necessary files could not be found in OLP_dir"

How should I resolve this?
Thank you.

**Comment by mzjb** [comment]
> Hello, author. When I use ABACUS for calculations, it outputs the corresponding SR.CSR file. The path has been confirmed in the configuration file, but an error occurs during the prediction process: assert os.path.exists(os.path.join(OLP_dir, 'SR.csr')), "Necessary files could not be found in OLP_dir"
> 
> How should I resolve this? Thank you.

Please check the exact filename in your OLP_dir. Is it SR.csr or SR.CSR?
If your file is named SR.CSR, this may be due to a change in ABACUS naming conventions. Renaming SR.CSR to SR.csr should resolve the issue.
