### ISSUE TITLE
question about van der Waals heterojunctions

### ISSUE THREAD

**Issue by yifei-zx** [mzjb/DeepH-pack#40]
Hi,
I found that the datasets with the double-layer structure in your article are all the same two layers. I would like to know if DeepH can be applied to van der Waals heterojunctions?

best regard.

**Comment by mzjb** [comment]
@yifei-zx
We have tested using DeepH-E3 to study several heterobilayer materials and have found that it can achieve similar accuracy to that of homobilayer materials.
