### ISSUE TITLE
question about step4_overlap

### ISSUE THREAD

**Issue by wangchengDon** [mzjb/DeepH-pack#48]
Dear developer, may I ask why it is necessary to calculate the overlay before using the model? If I could directly obtain the Hamiltonian of real space through the model, wouldn't it be possible to obtain any band through diagonalization?
  Can overlay help improve efficiency or have some other effects?

**Comment by mzjb** [comment]
If you're confused about what overlap means, I suggest you familiarize yourself with the concepts related to DFT calculations in non-orthogonal basis sets. You can also refer to the method section titled 'Physical properties derived from the DFT Hamiltonian' in the [DeepH article](https://www.nature.com/articles/s43588-022-00265-6).
