### ISSUE TITLE
error while preprocess in demo-abacus

### ISSUE THREAD

**Issue by yixiuzju** [mzjb/DeepH-pack#54]
Hello PhD.Li, I am a beginner in DeepH.
 When I tried to replicate the “demo: train the DeepH model using the Abacus interface” on the Bohrium platform, I encountered an error when I run step2-preprocess, the command line display:

preprocess.sh: 1: deeph-preprocess: not found

My preprocess.ini is
 [basic]
raw_dir = /data/demo_abacus/2_preprocess_dataset/3_dataset_graphene
processed_dir = ./preprocessed_3_graphene
target = hamiltonian
interface = abacus

[interpreter]
julia_interpreter = /home/lihe/apps/julia-1.5.4/bin/julia

[graph]
radius = -1
create_from_DFT = True

Because I am a beginner, I strictly followed the steps of the deep computer tutorial in BiliBili, I want to ask how I can solve this problem. looking forward to your reply.
best wishes.

**Comment by mzjb** [comment]
Hi,

It seems like an issue with the installation of DeepH in the Bohrium mirror. I haven't used Bohrium before, so I suggest reaching out to Bohrium's support team for assistance. Alternatively, you can refer to our documentation to install the DeepH environment yourself, or consider using other computing platforms compatible with DeepH, such as [TEFS](https://tefscloud.com/login).

Best.

**Comment by yixiuzju** [comment]
Thank you very much for your reply. I have resolved the above issue and thank you again for your help.
