### ISSUE TITLE
deeph-inference --config inference.ini error for ABACUS3.0.0

### ISSUE THREAD

**Issue by sgyang345** [mzjb/DeepH-pack#57]
An error occurred when using the **deeph-inference** function to obtain **overlaps.h5** from ABACUS 's get_s calculation.
The error message is included in the **deeph-inference.log** file.
In order to save space, I emptied the SR.csr file.
[get_S_process.zip](https://github.com/mzjb/DeepH-pack/files/12923926/get_S_process.zip)

**Comment by mzjb** [comment]
Thank you for your report, this issue has been fixed by PR #58.
