### ISSUE TITLE
Upgrade to new version of pyG and pytorch

### ISSUE THREAD

**Issue by Fadelis98** [mzjb/DeepH-pack#9]
Hello, because some hardware limit, i'm trying to use new version of pytorch and pyG with this package. Do you already know about what api changes caused the incompatibility of this package with new pytorch>1.9 and pytorch geometry>=2.0?

**Comment by mzjb** [comment]
I think PyTorch>=1.10 should be no problem.

The current DeepH-pack code is incompatible with PyG>=2.0, probably because the constructor of torch_geometric.data.Data has changed.

Pull requests which make DeepH-pack compatible with PyG 2.0 are welcome.

**Comment by mzjb** [comment]
PR #13 and [this commit](https://github.com/mzjb/DeepH-pack/commit/d6d052f78449f1790a97c03b2ea03d9cee3fc3ea) has made DeepH compatible with PyTorch = 1.12 and PyG = 2.1
